version: "3"
   
services:
  nginx:
    image: ulysseus/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-pod.conf:/etc/nginx/sites-enabled/pod.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/pod/static
      - ./logo.png:/var/www/pod/static/img/logo.png
      - ./brand-logo.png:/var/www/pod/static/img/brand-logo.png
      - ./favicon.ico:/var/www/pod/static/img/favicon.ico
      - ./media:/var/www/pod/media
      - ./uwsgi_params:/var/www/pod/uwsgi_params
      - ./socket:/var/www/pod/socket
      - /etc/certifs:/etc/ssl
    depends_on:
      - esup-pod

  esup-pod:
    image: ulysseus/esup-pod
    container_name: pod
    restart: always
    # command: python manage.py runserver 0.0.0.0:8000
    command: uwsgi --ini pod/custom/pod_uwsgi.ini
    # command: uwsgi --socket :8000 --wsgi-file pod/wsgi.py --enable-threads --master --processes 5 --threads 10
    volumes:
      - ./settings_local.py:/home/pod/Esup-Pod/pod/custom/settings_local.py
      - ./static:/home/pod/Esup-Pod/pod/static
      - ./media:/home/pod/Esup-Pod/pod/media
      - ./socket:/home/pod/Esup-Pod/pod/socket
    depends_on:
      - elasticsearch
    expose:
      - "8000"

  elasticsearch:
    container_name: elasticsearch
    image: ulysseus/elasticsearch
    restart: always
    command: /usr/share/elasticsearch/bin/elasticsearch
    environment:
    - JAVA_HOME=/opt/jdk-15.0.1+9
    - node.name=pod
    - discovery.type=single-node
    - http.host=0.0.0.0
    - transport.host=0.0.0.0
    volumes:
      - ./elasticsearch:/var/lib/elasticsearch
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    ports:
    - "9200:9200"
    - "9300:9300"
